[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solidity_version = '0.8.22'
evm_version = 'shanghai'
remappings = [
    "forge-std/=lib/forge-std/src",
    "openzeppelin/=lib/openzeppelin-contracts/contracts",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.blind-backrun]
src = 'blind-backrun/contracts/src'
test = 'blind-backrun/contracts/test'
out = 'blind-backrun/contracts/out'

[profile.basic]
src = 'basic/contracts/src'
test = 'basic/contracts/test'
out = 'basic/contracts/out'
