#![allow(clippy::all)]
//! This module contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod basic;
pub mod basic_only_search;
pub mod basic_only_settle;
pub mod basic_test;
pub mod common_base;
pub mod console;
pub mod console_2;
pub mod ds_test;
pub mod i_multicall_3;
pub mod ierc165;
pub mod ierc20;
pub mod ierc721;
pub mod ierc721_enumerable;
pub mod ierc721_metadata;
pub mod ierc721_token_receiver;
pub mod mock_erc20;
pub mod mock_erc721;
pub mod safeconsole;
pub mod script_base;
pub mod shared_types;
pub mod std_assertions;
pub mod std_chains;
pub mod std_cheats;
pub mod std_cheats_safe;
pub mod std_error;
pub mod std_invariant;
pub mod std_json;
pub mod std_math;
pub mod std_storage;
pub mod std_storage_safe;
pub mod std_style;
pub mod std_utils;
pub mod test;
pub mod test_base;
pub mod vm;
pub mod vm_safe;
