#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod basic;
pub mod basic_only_search;
pub mod basic_only_settle;
pub mod ierc165;
pub mod ierc20;
pub mod ierc721;
pub mod ierc721_enumerable;
pub mod ierc721_metadata;
pub mod ierc721_token_receiver;
pub mod mock_erc20;
pub mod mock_erc721;
